apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-app
spec:
  source:
    repoURL: https://github.com/sumitpurandare/argo-cd-manifests.git
    targetRevision: HEAD
    path: kustomize-files

    kustomize:
      version: v3.5.4