apiVersion: apps/v1
kind: Application
metadata: 
  name: nginx
  namespace: argocd
spec: 
  destination: 
    namespace: nginx
    server: "https://kubernetes.default.svc"
  project: default
  source: 
    path: kustomize-files
    repoURL: "https://github.com/sumitpurandare/argo-cd-manifests.git"
    targetRevision: main
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
  kustomize:
      version: v3.5.4

